### ISSUE TITLE
Incompatibility with bw2calc 2.0.DEV17

### ISSUE THREAD

**Issue by TimoDiepers** [romainsacchi/polyviz#3]
The latest bw2calc release 2.0.DEV17 removed the MonteCarloLCA class:

* Removed `MonteCarloLCA` (normal LCA class can do Monte Carlo) and added `IterativeLCA` (different solving strategy)
https://github.com/brightway-lca/brightway2-calc/blob/adc379e04929821c7f798cd3491242c80df67309/CHANGES.md?plain=1#L75

This currently breaks polyviz for this (and probably future) bw2calc versions: 
![image](https://github.com/romainsacchi/polyviz/assets/90762029/2b289bef-c409-4a61-9e4f-59fff2e6aee2)

**Comment by romainsacchi** [comment]
Should be fixed now with https://github.com/romainsacchi/polyviz/commit/c4bd4a0053c90be5874592985cf36905f745dfcc
